# Generated by Django 2.2.3 on 2019-10-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='操作人')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('protocol', models.CharField(default='ssh', max_length=64, verbose_name='协议')),
                ('port', models.SmallIntegerField(default=22, verbose_name='端口')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('cmd', models.TextField(blank=True, null=True, verbose_name='命令详情')),
                ('detail', models.CharField(blank=True, max_length=128, null=True, verbose_name='结果详情(文件名)')),
                ('address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('useragent', models.CharField(blank=True, max_length=512, null=True, verbose_name='User_Agent')),
                ('start_time', models.DateTimeField(verbose_name='会话开始时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='事件时间')),
            ],
            options={
                'verbose_name': '在线会话日志',
                'verbose_name_plural': '在线会话日志',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='会话名称')),
                ('group', models.CharField(default='chat_default', max_length=512, verbose_name='会话组')),
                ('type', models.SmallIntegerField(choices=[(1, 'webssh'), (2, 'websftp'), (3, 'clissh'), (4, 'clisftp'), (5, 'webtelnet'), (6, 'clitelnet'), (7, 'webrdp'), (8, 'webvnc')], default=1, verbose_name='类型')),
                ('user', models.CharField(max_length=128, verbose_name='用户')),
                ('host', models.GenericIPAddressField(verbose_name='主机')),
                ('port', models.SmallIntegerField(default=22, verbose_name='端口')),
                ('username', models.CharField(max_length=128, verbose_name='账号')),
                ('protocol', models.SmallIntegerField(choices=[(1, 'ssh'), (2, 'telnet'), (3, 'rdp'), (4, 'vnc'), (5, 'sftp'), (6, 'ftp')], default=1, verbose_name='协议')),
                ('address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('useragent', models.CharField(blank=True, max_length=512, null=True, verbose_name='User_Agent')),
                ('locked', models.BooleanField(default=False, verbose_name='会话状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='会话时间')),
            ],
            options={
                'verbose_name': '在线会话',
                'verbose_name_plural': '在线会话',
                'ordering': ['-create_time'],
            },
        ),
    ]
