# Generated by Django 2.2.3 on 2019-08-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='会话名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='会话时间')),
            ],
            options={
                'verbose_name': '在线会话',
                'verbose_name_plural': '在线会话',
            },
        ),
    ]
