# Generated by Django 2.2.3 on 2019-08-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0002_terminalsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsession',
            name='host',
            field=models.GenericIPAddressField(default='192.168.223.111', verbose_name='主机IP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminalsession',
            name='protocol',
            field=models.SmallIntegerField(choices=[(1, 'ssh'), (2, 'telnet'), (3, 'rdp'), (4, 'vnc'), (5, 'sftp'), (6, 'ftp')], default=1, verbose_name='协议'),
        ),
        migrations.AddField(
            model_name='terminalsession',
            name='user',
            field=models.CharField(default='admin', max_length=128, verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminalsession',
            name='username',
            field=models.CharField(default='root', max_length=128, verbose_name='账号'),
            preserve_default=False,
        ),
    ]
