# Generated by Django 2.2.3 on 2019-07-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0002_auto_20190729_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminallog',
            name='res',
        ),
        migrations.CreateModel(
            name='TerminalLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.TextField(default='未记录', verbose_name='结果详情')),
                ('terminallog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webssh.TerminalLog')),
            ],
            options={
                'verbose_name': '在线会话日志结果详情',
                'verbose_name_plural': '在线会话日志结果详情',
            },
        ),
    ]
