# Generated by Django 2.2.3 on 2019-08-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0003_auto_20190813_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsession',
            name='port',
            field=models.SmallIntegerField(default=22, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='terminalsession',
            name='host',
            field=models.GenericIPAddressField(verbose_name='主机'),
        ),
    ]
