# Generated by Django 2.2.3 on 2019-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0003_auto_20190730_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminallog',
            name='protocol',
            field=models.CharField(default='ssh', max_length=64, verbose_name='协议'),
        ),
    ]
