# Generated by Django 2.2.3 on 2019-08-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0006_terminalsession_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminallog',
            name='detail',
            field=models.CharField(default='result', max_length=128, verbose_name='结果详情(文件名)'),
        ),
        migrations.DeleteModel(
            name='TerminalLogDetail',
        ),
    ]
