# Generated by Django 2.2.3 on 2019-08-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0007_auto_20190827_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsession',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='terminalsession',
            name='useragent',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='User_Agent'),
        ),
    ]
