# Generated by Django 2.2.3 on 2019-09-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0008_auto_20190829_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminallog',
            name='cmd',
            field=models.TextField(blank=True, null=True, verbose_name='命令详情'),
        ),
        migrations.AlterField(
            model_name='terminallog',
            name='detail',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='结果详情(文件名)'),
        ),
        migrations.AlterField(
            model_name='terminalsession',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'webssh'), (2, 'websftp'), (3, 'clissh'), (4, 'clisftp'), (5, 'webtelnet'), (6, 'clitelnet'), (7, 'webrdp'), (8, 'webvnc')], default=1, verbose_name='类型'),
        ),
    ]
