# Generated by Django 2.2.3 on 2019-09-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0009_auto_20190902_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsession',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='会话状态'),
        ),
    ]
