# Generated by Django 2.2.3 on 2019-08-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0004_auto_20190813_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminalsession',
            options={'ordering': ['-create_time'], 'verbose_name': '在线会话', 'verbose_name_plural': '在线会话'},
        ),
        migrations.AddField(
            model_name='terminalsession',
            name='group',
            field=models.CharField(default='chat_default', max_length=512, verbose_name='会话组'),
        ),
    ]
