# Generated by Django 2.2.3 on 2019-10-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_auto_20191018_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcmdlog',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '命令'), (2, '脚本'), (3, '上传文件')], default=1, verbose_name='类型'),
        ),
    ]
