apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{component_name}}
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: {{component_name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{component_name}}
    spec:
      initContainers:
        - name: init-redis-service
          image: hub.leffss.com/library/busybox:v1.28.4
          command: ['sh', '-c', 'until nslookup redis-service; do echo waiting for redis-service; sleep 3; done;']
        - name: init-mysql-service
          image: hub.leffss.com/library/busybox:v1.28.4
          command: ['sh', '-c', 'until nslookup mysql-service; do echo waiting for mysql-service; sleep 3; done;']
      containers:
      - name: daphne
        image: {{img_url}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: devops-pvc
          mountPath: "/devops/media"
        command: ["supervisord","-c","/etc/supervisord_devops_daphne.conf"]
      volumes:
      - name: devops-pvc
        persistentVolumeClaim:
          claimName: devops-cephfs-share-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{component_name}}
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector: 
    app: {{component_name}}
