# Generated by Django 2.2.3 on 2019-10-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, verbose_name='组名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=512, verbose_name='密码')),
                ('enabled', models.BooleanField(default=False, verbose_name='登陆后是否su跳转超级用户')),
                ('superusername', models.CharField(blank=True, max_length=128, null=True, verbose_name='超级用户')),
                ('superpassword', models.CharField(blank=True, max_length=512, null=True, verbose_name='超级密码')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '主机账户',
                'verbose_name_plural': '主机账户',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='RemoteUserBindHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('type', models.SmallIntegerField(choices=[(1, '服务器'), (2, '防火墙'), (3, '路由器'), (4, '二层交换机'), (5, '三层交换机'), (6, '虚拟机'), (7, 'PC机')], default=1, verbose_name='类型')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('wip', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')),
                ('protocol', models.SmallIntegerField(choices=[(1, 'ssh'), (2, 'telnet'), (3, 'rdp'), (4, 'vnc'), (5, 'sftp'), (6, 'ftp')], default=1, verbose_name='协议')),
                ('env', models.SmallIntegerField(choices=[(1, '正式环境'), (2, '测试环境')], default=1, verbose_name='环境')),
                ('port', models.SmallIntegerField(default=22, verbose_name='端口')),
                ('release', models.CharField(default='CentOS', max_length=255, verbose_name='系统/型号')),
                ('platform', models.SmallIntegerField(choices=[(1, 'linux'), (2, 'windows'), (3, 'unix')], default=1, verbose_name='平台')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('host_group', models.ManyToManyField(blank=True, to='server.HostGroup', verbose_name='主机组')),
                ('remote_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.RemoteUser')),
            ],
            options={
                'verbose_name': '远程主机',
                'verbose_name_plural': '远程主机',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ServerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号')),
                ('cpu_number', models.SmallIntegerField(blank=True, null=True, verbose_name='物理CPU个数')),
                ('vcpu_number', models.SmallIntegerField(blank=True, null=True, verbose_name='逻辑CPU个数')),
                ('disk_total', models.CharField(blank=True, max_length=16, null=True, verbose_name='磁盘空间')),
                ('ram_total', models.SmallIntegerField(blank=True, null=True, verbose_name='内存容量')),
                ('swap_total', models.SmallIntegerField(blank=True, null=True, verbose_name='交换空间容量')),
                ('kernel', models.CharField(blank=True, max_length=128, null=True, verbose_name='内核版本')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='操作系统')),
                ('filesystems', models.TextField(blank=True, null=True, verbose_name='文件系统')),
                ('interfaces', models.TextField(blank=True, null=True, verbose_name='网卡信息')),
                ('server_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='型号')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.RemoteUserBindHost')),
            ],
            options={
                'verbose_name': '主机详细',
                'verbose_name_plural': '主机详细',
            },
        ),
    ]
