# Generated by Django 2.2.3 on 2019-07-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('port', models.SmallIntegerField(default=22, verbose_name='端口')),
                ('release', models.CharField(default='CentOS', max_length=255, verbose_name='发行版本')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'ordering': ['-create_time'],
                'unique_together': {('ip', 'port')},
            },
        ),
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=512, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '主机账户',
                'verbose_name_plural': '主机账户',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='RemoteUserBindHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Host')),
                ('remote_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.RemoteUser')),
            ],
            options={
                'verbose_name': '远程主机',
                'verbose_name_plural': '远程主机',
                'ordering': ['-create_time'],
                'unique_together': {('host', 'remote_user')},
            },
        ),
    ]
