# Generated by Django 2.2.3 on 2019-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='wip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP'),
        ),
        migrations.AddField(
            model_name='remoteuser',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
