# Generated by Django 2.2.3 on 2019-10-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='归属用户'),
        ),
        migrations.AlterUniqueTogether(
            name='remoteuserbindhost',
            unique_together={('ip', 'protocol', 'port', 'remote_user')},
        ),
        migrations.AlterUniqueTogether(
            name='hostgroup',
            unique_together={('group_name', 'user')},
        ),
    ]
