# Generated by Django 2.2.3 on 2019-07-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190729_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='登陆后是否su调转超级用户'),
        ),
        migrations.AddField(
            model_name='remoteuser',
            name='superpassword',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='超级密码'),
        ),
        migrations.AddField(
            model_name='remoteuser',
            name='superusername',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='超级用户'),
        ),
    ]
