# Generated by Django 2.2.3 on 2019-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190923_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetail',
            name='swap_total',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='交换空间容量'),
        ),
    ]
