# Generated by Django 2.2.3 on 2019-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_serverdetail_swap_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetail',
            name='server_model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='型号'),
        ),
    ]
