# Generated by Django 2.2.3 on 2019-07-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190730_1544'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('ip', 'protocol', 'port')},
        ),
    ]
