# Generated by Django 2.2.3 on 2019-09-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190909_0854'),
        ('server', '0005_serverdetail_server_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, verbose_name='组名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='归属用户')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
                'unique_together': {('group_name', 'user')},
            },
        ),
        migrations.AddField(
            model_name='remoteuserbindhost',
            name='host_group',
            field=models.ManyToManyField(blank=True, null=True, to='server.HostGroup', verbose_name='主机组'),
        ),
    ]
