# Generated by Django 2.2.3 on 2019-07-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20190730_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuserbindhost',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Host'),
        ),
        migrations.AlterField(
            model_name='remoteuserbindhost',
            name='remote_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.RemoteUser'),
        ),
    ]
