# Generated by Django 2.2.3 on 2019-07-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190731_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '其他'), (1, '服务器'), (2, '防火墙'), (3, '路由器'), (4, '二层交换机'), (5, '三层交换机'), (6, '虚拟机'), (7, 'PC机')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='release',
            field=models.CharField(default='CentOS', max_length=255, verbose_name='系统/型号'),
        ),
    ]
