# Generated by Django 2.2.3 on 2019-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20190731_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='env',
            field=models.SmallIntegerField(choices=[(0, '其他'), (1, '正式环境'), (2, '测试环境')], default=1, verbose_name='环境'),
        ),
    ]
