# Generated by Django 2.2.3 on 2019-10-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, unique=True, verbose_name='组名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('remote_user_bind_hosts', models.ManyToManyField(blank=True, to='server.RemoteUserBindHost', verbose_name='组内关联的远程主机')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户')),
                ('event_type', models.SmallIntegerField(choices=[(1, '登陆'), (2, '退出'), (3, '登陆错误'), (4, '修改密码失败'), (5, '修改密码成功'), (6, '添加用户'), (7, '删除用户'), (8, '添加组'), (9, '删除组'), (10, '更新用户'), (11, '更新组'), (12, '添加主机'), (13, '删除主机'), (14, '更新主机'), (15, '添加主机用户'), (16, '删除主机用户'), (17, '更新主机用户'), (18, '停止在线会话'), (19, '锁定在线会话'), (20, '解锁在线会话'), (21, '添加主机组'), (22, '删除主机组'), (23, '更新主机组')], default=1, verbose_name='事件类型')),
                ('detail', models.TextField(default='登陆成功', verbose_name='事件详情')),
                ('address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('useragent', models.CharField(blank=True, max_length=512, null=True, verbose_name='User_Agent')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='事件时间')),
            ],
            options={
                'verbose_name': '用户日志',
                'verbose_name_plural': '用户日志',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32, verbose_name='性别')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('role', models.SmallIntegerField(choices=[(1, '超级管理员'), (2, '普通用户')], default=2, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('weixin', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信')),
                ('qq', models.CharField(blank=True, max_length=24, null=True, verbose_name='QQ')),
                ('setting', models.TextField(blank=True, default='{"clissh": [{"name": "securecrt", "path": "C:\\\\Program Files\\\\VanDyke Software\\\\Clients\\\\SecureCRT.exe", "args": "/T /N \\"{username}@{host}-{hostname}\\" /SSH2 /L {login_user} /PASSWORD {login_passwd} {login_host} /P {port}", "enable": true}, {"name": "xshell", "path": "C:\\\\Program Files (x86)\\\\NetSarang\\\\Xmanager Enterprise 5\\\\Xshell.exe", "args": "-newtab \\"{username}@{host}-{hostname}\\" -url ssh://{login_user}:{login_passwd}@{login_host}:{port}", "enable": false}, {"name": "putty", "path": "C:\\\\Users\\\\xx\\\\AppData\\\\Roaming\\\\TP4A\\\\Teleport-Assist\\\\tools\\\\putty\\\\putty.exe", "args": "-l {login_user} -pw {login_passwd} {login_host} -P {port}", "enable": false}, {"name": "custom", "path": "", "args": "", "enable": false}], "clisftp": [{"name": "winscp", "path": "C:\\\\Program Files\\\\winscp\\\\WinSCP.exe", "args": "/sessionname=\\"{username}@{host}-{hostname}\\" {login_user}:{login_passwd}@{login_host}:{port}", "enable": true}, {"name": "custom", "path": "", "args": "", "enable": false}]}', null=True, verbose_name='设置')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('groups', models.ManyToManyField(blank=True, to='user.Group', verbose_name='所属组')),
                ('remote_user_bind_hosts', models.ManyToManyField(blank=True, to='server.RemoteUserBindHost', verbose_name='用户关联的远程主机')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-create_time'],
            },
        ),
    ]
