# Generated by Django 2.2.3 on 2019-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='group',
            name='remote_user_bind_hosts',
            field=models.ManyToManyField(blank=True, to='server.RemoteUserBindHost', verbose_name='组内关联的远程主机'),
        ),
        migrations.AlterField(
            model_name='user',
            name='remote_user_bind_hosts',
            field=models.ManyToManyField(blank=True, to='server.RemoteUserBindHost', verbose_name='用户关联的远程主机'),
        ),
    ]
