# Generated by Django 2.2.3 on 2019-08-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190731_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='user',
            name='weixin',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信'),
        ),
    ]
